apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: traefik
    repoURL: https://github.com/icosamuel/kubernatorz
    targetRevision: HEAD
  sources: []
  project: default
