apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    path: argo-cd
    repoURL: https://github.com/icosamuel/kubernatorz
    targetRevision: HEAD
  sources: []
  project: argo-cd
