apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "1.0"

dependencies:
- name: argo/argo-cd
  version: 9.0.3
  repository: https://argoproj.github.io/argo-helm